Repository informatique-cdc/ebad, pull requests merged in 2020-09, with the labels that each got.

#48 Fix default params which isn't used
  src/main/java/fr/icdc/ebad/service/BatchService.java
Labels: bug

#49 [SECURITY] CVE-2019-16303 - JHipster Vulnerability Fix - Use CSPRNG in RandomUtil
  src/main/java/fr/icdc/ebad/service/util/RandomUtil.java
Labels: security

#51 Feature/parsing jodatime
  pom.xml
  src/main/java/fr/icdc/ebad/web/rest/errors/ExceptionTranslator.java
  src/main/resources/config/application.yml
Labels: bug

#55 add endpoint to delete batch
  src/main/java/fr/icdc/ebad/web/rest/BatchResource.java
  src/test/java/fr/icdc/ebad/web/rest/BatchResourceTest.java
Labels: enhancement

#58 fix xss
  src/main/java/fr/icdc/ebad/web/rest/AccountResource.java
  src/test/java/fr/icdc/ebad/web/rest/AccountResourceTest.java
Labels: bug, security

#59 Feature/file explorer
  pom.xml
  src/main/java/fr/icdc/ebad/domain/Directory.java
  src/main/java/fr/icdc/ebad/security/permission/PermissionDirectory.java
  src/main/java/fr/icdc/ebad/service/DirectoryService.java
  src/main/java/fr/icdc/ebad/service/ShellService.java
  src/main/java/fr/icdc/ebad/web/rest/DirectoryResource.java
  src/main/java/fr/icdc/ebad/web/rest/dto/DirectoryDto.java
  src/main/java/fr/icdc/ebad/web/rest/dto/FilesDto.java
  src/main/resources/db/changelog/changeset/2.2.2-1-changeset.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/test/java/fr/icdc/ebad/security/permission/PermissionDirectoryTest.java
  src/test/java/fr/icdc/ebad/service/DirectoryServiceTest.java
  src/test/java/fr/icdc/ebad/service/ShellServiceTest.java
  src/test/java/fr/icdc/ebad/web/rest/DirectoryResourceTest.java
  src/test/resources/config/application-test.yml
Labels: enhancement
